<?php

namespace AppBundle\Repository;

/**
 * BlockContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockContentRepository extends \Doctrine\ORM\EntityRepository
{
}
