<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubCategories()
    {
        $qb = $this->createQueryBuilder('sc');
        $qb->where('sc.parentCategory != :category')
            ->orderBy('sc.name')
            ->setParameter('category', 0);

        return $qb->getQuery()
            ->getResult();
    }
}
