<?php

namespace AppBundle\Repository;

/**
 * CMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSRepository extends \Doctrine\ORM\EntityRepository
{
}
