<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByCategory($category)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->join('AppBundle:Category', 'cat', 'WITH', 'c.category = cat')
            ->where('cat = :category')
            ->orWhere('cat.parentCategory = :category')
            ->andWhere('c.status = :status')
            ->setParameter('category', $category)
            ->setParameter('status', 1);

        return $qb->getQuery()
            ->getResult();
    }

    public function getSuggestions($content)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.category = :category')
            ->andWhere('c.status = :status')
            ->andWhere('c.id != :content_id')
            ->setParameter('category', $content->category)
            ->setParameter('content_id', $content->id)
            ->setParameter('status', 1);

        return $qb->getQuery()
            ->getResult();
    }
}
