<?php

namespace AppBundle\Repository;

/**
 * LobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LobbyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextLobbies()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->where('l.date_start >= :date')
            ->setParameter('date', date("Y-m-d H:i:s"));

        return $qb->getQuery()
            ->getResult();
    }
}
