<?php

namespace AppBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotesForLobby($lobby, $user_ids)
    {

        $in = '(';
        foreach ($user_ids as $k => $user_id) {
            if ($k > 0) {
                $in .= ',';
            }
            $in .= $user_id;
        }
        $in .= ')';
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.content != :content')
            ->andWhere('n.user IN '.$in)
            ->setParameter('content', $lobby->content);

        return $qb->getQuery()
            ->getResult();
    }
}
