<?php

namespace AppBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotesForLobby($lobby, $user_ids)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.content != :content')
            ->andWhere('n.user IN :user_ids')
            ->setParameter('content', $lobby->content)
            ->setParameter('user_ids', $user_ids);

        return $qb->getQuery()
            ->getResult();
    }
}
