app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@AppBundle/Controller/API'
    type: annotation
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin