# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.form.profile:
      class: AppBundle\Form\ProfileFormType
      tags:
        - { name: form.type, alias: app_user_profile_edit }
