# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.form.profile:
      class: AppBundle\Form\ProfileFormType
      tags:
        - { name: form.type, alias: app_user_profile_edit }
    app.util.api_manager:
      class: AppBundle\Services\ApiManager
      arguments: ['%api_key%', '%api_host%', '%oauth_client%', '%oauth_secret%']
    app.kernel_listener:
        class: AppBundle\EventListener\KernelListener
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }